server:
  port: 7021

spring:
  application:
    name: eureka-server-7021

eureka:
  instance:
    hostname: eureka01.com
  client:
    register-with-eureka: false #false 表示不向注册中心 注册自己
    fetch-registry: false #false 表示自己是注册中心
    service-url:
      #关联另一个注册中心
      defaultZone: http://eureka02.com:7022/eureka/