server:
  port: 9010

spring:
  application: learning-01-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.207.144.186:3306/shop?characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    dbcp2:
      min-idle: 5
      max-idle: 10
      initial-size: 5
      max-wait-millis: 200
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.jero.springcloud.pojo.user
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true




